baseURL = 'https://nezutero.dev'
languageCode = 'en-us'
title = "nezutero's blog"

[taxonomies]
tag = 'tags'

[params]
# Home meta description
description = "A non-oriented (maybe a bit) personal website-blog"
footerMark = "/brainmade.png"
footerMarkLink = "https://brainmade.org"

# Appearance settings
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content in markdown
homeIntroTitle = "I think therefore I am"
homeIntroContent = """
I'm Dimitri Nesterenko, a software engineer interested in various topics, including algorithms, math, Linux and FOSS, philosophy, and reading. 

This website is my connector to the world and my public journal, where I share thoughts and experiences that I hope will be useful or interesting to someone.

Feel free to read more [about me](/about) or explore my [posts](/posts).
"""

singleDateFormat = '2 January 2006'

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = '2 Jan 2006'

# Footer
showFooter = true

# Breadcrumbs
[params.breadcrumbs]
enabled = false
showCurrentPage = false
home = "~"

# Social links
[[params.social]]
name = "Github"
url = "https://github.com/nezutero"

[[params.social]]
name = "Linkedin"
url = "https://www.linkedin.com/in/nezutero/"

[[params.social]]
name = "Email"
url = "mailto:me@nezutero.dev"

[[params.social]]
name = "RSS"
url = "/posts/index.xml"

# Main menu pages
# [[params.menu]]
# name = "home"
# url = "/"

[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Posts"
url = "/posts"

[[params.menu]]
name = "About"
url = "/about"

[[params.menu]]
name = "Library"
url = "/library"

[[params.menu]]
name = "Tags"
url = "/tags"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'gruvbox'

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

[params.umami]
enable = true
websiteId = "9d9e66a4-4214-4dd3-a073-8ee1299060b2"
jsLocation = "https://cloud.umami.is/script.js"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
